name: Java CI with Maven and TestNG

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_test:
    runs-on: windows-latest

    steps:
       - uses: actions/checkout@v3
       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
          
          java-version: '17'
          distribution: 'temirin'
       - name: Build with Maven
         run: mvn -B package --file pom.xml

  publish-job:
    runs-on: windows-latest
     
    steps:
       - uses: actions/checkout@v3
       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
          java-version: '17'
          distribution: 'temirin'
       - name: Run Tests
         run: mvn test
