name: Java CI with Maven and TestNG

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up Maven
        uses: actions/setup-maven@v2
        with:
          maven-version: '4.0.0'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
     
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Set up Maven
        uses: actions/setup-maven@v2
        with:
          maven-version: '4.0.0'
      - name: Run Tests
        run: |
          echo "Current directory: $(pwd)"
          ls -R
          mvn test
