name: Java CI with Maven, Selenium, and TestNG

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  selenium-test:
    runs-on: ubuntu-latest
     
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run Tests  
        run: |
          LATEST_RELEASE=$(curl -sSL https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          curl -sSL https://chromedriver.storage.googleapis.com/${LATEST_RELEASE}/chromedriver_linux64.zip -o chromedriver.zip
          unzip chromedriver.zip -d /usr/local/bin
          chmod +x /usr/local/bin/chromedriver
      - name: Run Selenium Tests
        run: mvn test -Dtest=tests.practiceTestAutomationTests.LoggedInSuccessfullyPageTests,tests.practiceTestAutomationTests.LoginPageTests
